language: node_js

node_js:
  - node

install:
  - npm ci

script:
  - npm test


after_script: ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
